from typing import Literal

from pydantic import BaseModel, Field

from evaluation_utils import llm_structured_retry


class AnswerEvaluation(BaseModel):
    reasoning: str = Field(
        description="Reasoning about whether the AI answer recommends the ground-truth model or an equally valid one."
    )
    score: Literal["good", "bad"] = Field(
        description=(
            "'good' if the recommended model satisfies the query as well as the ground-truth model, "
            "'bad' otherwise."
        )
    )


JUDGE_INSTRUCTIONS = """
You are an expert evaluator for an assistant that recommends pretrained
models from the Hugging Face Hub for a user's ML task.

You will be given:
1. A user's description of the ML task they want to solve
2. The model that is the known correct match for this query (ground truth),
   with its id, task, languages and a short card summary
3. An answer generated by an AI assistant, which recommends a model from
   a set of retrieved candidates

Your task is to decide whether the AI's answer successfully recommends
a model that solves the user's query.

Rules:
- The model id doesn't need to match exactly in casing, and a missing or
  different org prefix is fine as long as it clearly refers to the same repo
- Mark 'good' if the ground-truth model is clearly recommended as the best
  match or one of the top options
- Also mark 'good' if the AI recommends a different model that, based on the
  answer's own description of it, satisfies every constraint in the query
  (task, language, domain, size, etc.) at least as well as the ground-truth
  model. Say explicitly in your reasoning when this rule applied
- Mark 'bad' if the recommendation does the wrong task, misses a constraint
  stated in the query, or the answer itself says none of the candidates fit
- Be fair and focus on correctness, not writing style
""".strip()

JUDGE_PROMPT_TEMPLATE = """
Query:
{query}

Correct model (ground truth):
{correct_model}

AI answer:
{ai_answer}
""".strip()


def evaluate_answer(client, query, correct_model, ai_answer, model="gpt-5.4-mini"):
    prompt = JUDGE_PROMPT_TEMPLATE.format(
        query=query,
        correct_model=correct_model,
        ai_answer=ai_answer,
    )

    return llm_structured_retry(
        client,
        JUDGE_INSTRUCTIONS,
        prompt,
        AnswerEvaluation,
        model=model,
    )
