from typing import Literal

from pydantic import BaseModel, Field

from evaluation_utils import llm_structured_retry


class AnswerEvaluation(BaseModel):
    reasoning: str = Field(
        description="Reasoning about whether the AI answer correctly surfaces the ground-truth anime."
    )
    score: Literal["good", "bad"] = Field(
        description="'good' if the correct anime is clearly identified as a strong match, 'bad' otherwise."
    )


JUDGE_INSTRUCTIONS = """
You are an expert evaluator for an anime recommendation assistant.

You will be given:
1. A user's plot/vibe description query
2. The title of the anime that is the known correct match for this query (ground truth)
3. An answer generated by an AI assistant, which recommends one or more
   anime from a set of retrieved candidates

Your task is to decide whether the AI's answer successfully surfaces
the correct anime as a strong match.

Rules:
- The AI answer does not need to use the exact same title spelling/romanization
- Mark 'good' if the correct anime is clearly identified as the best
  match or one of the top options
- Mark 'bad' if the correct anime is missing entirely, dismissed, or
  only mentioned as a weak/incidental option below a clearly preferred
  wrong answer
- Be fair and focus on correctness, not writing style
""".strip()

JUDGE_PROMPT_TEMPLATE = """
Query:
{query}

Correct anime (ground truth):
{correct_title}

AI answer:
{ai_answer}
""".strip()


def evaluate_answer(client, query, correct_title, ai_answer, model="gpt-5.4-mini"):
    prompt = JUDGE_PROMPT_TEMPLATE.format(
        query=query,
        correct_title=correct_title,
        ai_answer=ai_answer,
    )

    return llm_structured_retry(
        client,
        JUDGE_INSTRUCTIONS,
        prompt,
        AnswerEvaluation,
        model=model,
    )
