apiVersion: v1
kind: Service
metadata:
  name: anime-finder-app
  namespace: anime-finder
spec:
  type: ClusterIP
  selector:
    app: anime-finder
    component: app
  ports:
    - name: http
      port: 80
      targetPort: 8501
