apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hf-model-finder-ingress
  namespace: hf-model-finder
spec:
  ingressClassName: nginx
  rules:
    - host: hf-model-finder.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hf-model-finder-app
                port:
                  number: 80
    - host: dashboard.hf-model-finder.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hf-model-finder-dashboard
                port:
                  number: 80
